server:
  port: 8080
spring:
  application:
    name: dolphin-backend
  datasource:
    url: jdbc:mysql://localhost:3306/test1
    username: root
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver

