server:
  port: 8099
spring:
  application:
    name: dolphin-backend
  datasource:
    url: jdbc:mysql://localhost:3306/doplin
    username: root
    password: 19930205
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:sqlmap/*.xml

