server:
  port: 8088
spring:
  application:
    name: dolphin
  datasource:
    url: jdbc:mysql://123.56.249.169:3306/dolphin
    username: root
    password: Hbg!wZGeZ942T!X
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  configuration:
    map-underscore-to-camel-case: true